// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/minkj1992/fiber-wire/entity"
)

// Injectors from wire.go:

func InitializeEvent() entity.Event {
	message := entity.NewMessage()
	greeter := entity.NewGreeter(message)
	event := entity.NewEvent(greeter)
	return event
}
