// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/minkj1992/go-playground/wire/entity"
)

// Injectors from wire.go:

func InitializeEvent(phrase string) (entity.Event, error) {
	message := entity.NewMessage(phrase)
	greeter := entity.NewGreeter(message)
	event, err := entity.NewEvent(greeter)
	if err != nil {
		return entity.Event{}, err
	}
	return event, nil
}
